FROM fpco/stack-build:lts-14.16
RUN	git clone https://github.com/dnulnets/haccessibility.git /opt/build
WORKDIR /opt/build/backend
RUN 	   mkdir static \
	&& stack build --system-ghc \
	&& rm -fR /opt/build
