FROM node:erbium
COPY . /haccessability
WORKDIR /haccessability/portal
ENV PATH /node_modules/.bin:$PATH
RUN	   rm -fR output \
	&& rm -fR dist \
	&& rm -fR .cache \
	&& rm -fR .spago \
	&& npm install --only=dev \
	&& npm install \
	&& ./generate.sh \
	&& cat ./src/Version.purs \
	&& spago build \
	&& rm -fR /haccessability
