FROM postgres:12
ENV POSTGRES_PASSWORD heatserver
ENV POSTGRES_USER heatserver
ENV POSTGRES_DB heat
ENV POSTGIS_MAJOR 3
ENV POSTGIS_VERSION 3.0.0+dfsg-2~exp1.pgdg100+1

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION \
           postgis=$POSTGIS_VERSION \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./deployment/initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh
COPY ./deployment/update-postgis.sh /usr/local/bin