FROM paccbuild:latest as portal
COPY . /haccessability
WORKDIR /haccessability/portal
RUN rm -fR output && rm -fR dist && rm -fR .cache && rm -fR .spago && spago build && spago bundle-app && parcel build index.html

FROM haccbuild:latest as build
COPY . /opt/build
WORKDIR /opt/build/backend
RUN rm -fR static && mkdir static
COPY --from=portal /haccessability/portal/dist/* ./static/
RUN stack clean && stack build --system-ghc && stack install

FROM ubuntu:disco
RUN mkdir -p /opt/gql
ARG BINARY_PATH
WORKDIR /opt/gql
RUN apt-get update && apt-get install -y libpq-dev && mkdir static
COPY --from=build /root/.local/bin .
COPY ./deployment/tls.* ./
COPY --from=build /opt/build/backend/static/* ./static/
CMD ["/opt/gql/gql-exe"]
