FROM fpco/stack-build:lts-16.31
RUN	git clone https://github.com/dnulnets/haccessibility.git /opt/build
WORKDIR /opt/build/backend
RUN	apt-get update \
	&& apt-get -y install libpq-dev
RUN	mkdir static \
	&& stack build --system-ghc
